TaskarCenterAtUW/TDEI-user-management-front-end

.github/workflows/deploy_to_stage.yaml
Added separate workflow for stage.
=> Added workflow for stage

tdei-ui/public/index.html
Minor fix for title
- This is to test the github action
=> minor change

.github/workflows/deploy_to_dev.yaml
variables changed to vars context as per environment documentation
=> change in variable

.github/workflows/deploy_to_dev.yaml
creates the env file after checkout
=> create after checkout

.github/workflows/deploy_to_dev.yaml
=> indentation issue

.gitignore, tdei-ui/.env.example
Removed the env file from the source code
=> deleted env file

tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/components/CreateOrganisation/CreateOrganisation.js, tdei-ui/src/components/ManagePoc/ManagePoc.js, tdei-ui/src/utils/constant.js
Fixed Bugs : 
1. 409 : Incorrect "poc deleted" error message.
2. 410 : Better Error Messages for Mal formatted number.
3. 411 : Page doesn't exist on login.
Screenshots :
=> Fixed Bugs : 409, 410 and 411

tdei-ui/src/components/ProjectGroupList/ProjectGrpList.js, tdei-ui/src/hooks/projectGroup/useGetProjectGroup.js
- fixes the error caused when admin tries to add a service. The issue was with the difference in the naming of the parameter.
=> Bugfix admin dropdown

tdei-ui/src/routes/Services/Services.js, tdei-ui/src/routes/Stations/Stations.js
- Fixed create new station navigation bug where it was displaying old create station modal instead of new page.
- Removed Lorem Ipsum dummy text being displayed in admin view of create new station/service
=> Fixed create new station navigation bug

tdei-ui/src/components/ForgotPassModal/ForgotPassModal.js, tdei-ui/src/components/UserHeader/UserHeader.js, tdei-ui/src/components/UserHeader/UserHeader.module.css, tdei-ui/src/routes/LoginPage/LoginPage.js, tdei-ui/src/routes/ProjectGroup/ProjectGroup.js, tdei-ui/src/routes/Services/ClipBoardCopy.js, tdei-ui/src/routes/Services/Services.js
1. Added project id as a part of display in :
- Dashboard screen (for non-admin)
- List of project groups (for admin)
2. Added forgot password button which on click display a modal.
=> Added project id and forgot password features

.github/workflows/deploy_to_dev.yaml, .github/workflows/deploy_to_stage.yaml
Added admin email in the .env for deployment
=> Added admin email

.github/workflows/deploy_to_dev.yaml, .github/workflows/deploy_to_stage.yaml
Changed variable appropriately
=> changed variable appropriately

tdei-ui/src/routes/Register/Register.js
Made the necessary changes :
- On successful registration user is navigated to dashboard.
- Added asterisk for all required fields i,e first name, email, password & confirm password.
- Submit button is disabled until all required fields have been filled out.
- Validating fields on editing complete for all fields.
=> Task #573 : User Management Front End Review Feedback

tdei-ui/src/hooks/service/useGetServices.js, tdei-ui/src/hooks/station/useGetStations.js, tdei-ui/src/routes/Services/CreateUpdateService.js, tdei-ui/src/routes/Services/Services.js, tdei-ui/src/routes/Services/Services.module.css, tdei-ui/src/routes/Stations/CreateUpdateStation.js, tdei-ui/src/routes/Stations/Stations.js, tdei-ui/src/routes/Stations/Stations.module.css, tdei-ui/src/services/apiServices.js
- Made changes in get services/stations api call and UI so that admin can also view list of all stations/services.
- When admin tries to edit station/service, project group ID field is disabled and rest all fields are enabled.
-  When admin tries to create new station/service, project group name dropdown is available to select project group name and rest all fields.
- Implemented this -> A user should be able to see the stations/services within the project groups they belong to, but should not have ability to create, update or delete
User who is not admin and POC but assigned to some project group, cannot view list of services/stations : 
User who is not admin and POC and not assigned to any project group, cannot view list of services/stations :
=> Feature admin services stations list change

.github/workflows/deploy_to_dev.yaml, .github/workflows/deploy_to_stage.yaml, README.md
changed the name to usermanagement-web
- modified the publish pipelines
=> modified pipelines

.gitignore, tdei-ui/src/components/ColoredLabel/ColoredLabel.js, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/hooks/jobs/useCreateJob.js, tdei-ui/src/hooks/jobs/useGetJobs.js, tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css, tdei-ui/src/services/apiServices.js, tdei-ui/src/utils/constant.js, tdei-ui/src/utils/react-query-constant.js
API call for job creation,
Removed stations from navigation,
Ui fixes, sorting and refresh option in Jobs
=> feature job creation

tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js
=> Added dataset id in datasets list page

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css
=> Changes jobs preview accesses and minor UI changes

.github/workflows/deploy_to_dev.yaml, .github/workflows/deploy_to_stage.yaml
Added workspace url in the workflow
The values are added in variables respectively for both dev and stage
=> workspace url added

.github/workflows/deploy_to_dev.yaml, .github/workflows/deploy_to_stage.yaml
=> added REACT_APP_ prefix to variable

tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Datasets/DatasetTableHeader.js, tdei-ui/src/routes/Datasets/Datasets.module.css, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/services/apiServices.js
=> Updated Action item to open in workspace

tdei-ui/src/assets/sample_metadata.json, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js, tdei-ui/src/routes/UploadDataset/UploadDataset.js, tdei-ui/src/services/apiServices.js
- Multiple file-types upload done
- Job status stuff messaging corrected
- Navigation after the file successfully uploaded is also fixed
=> Bugfix multiple file types

tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/CollectedMethod.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/DataSource.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/DataTypeDropdown.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js
- Fixed the flickering issue while trying to edit/upload the dataset fields.
=> Feature-Bug-1019-Edit metadata fields are not getting updated 

tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js
Fixed the following issue: 
when a character is entered and trying to delete it and press the backspace, it doesn't disappear.
=> Feature bug 1019 delete issue

tdei-ui/src/routes/Datasets/DatasetsActions.js
-Fixed the following bug: 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1023
1. Admin user access: 
2. POC user access: 
3. Data generator user access: 
4. Admin user access -> Released Dataset : 
5. POC user access -> Released Dataset : 
6. Data generator user access -> Released Dataset :
=> Feature-Bug-1023-Deactivate operation must be enabled for pre-release datasets

tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/services/apiServices.js
Fixed bug: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1037
=> Feature-Bug-1037-JSON Data display issue after upon error dismiss

tdei-ui/src/routes/Datasets/ReleasedDatasets.js
Fixed the bug : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1071
=> Feature-Bug-1071-clone data button issue in released datasets tab

tdei-ui/src/components/ShowJobMessage/JobMsgDescModal.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/services/apiServices.js
1. Fixed bug : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1049
2. Implemented the new UX for job status progress.
3. Added validations to create job feature.
=> Feature-Bug-1049-Upload dataset for OSW- Convert during new Job creation failed

tdei-ui/src/services/apiServices.js
Fixed bug : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1115
Before : 
After:
=> Feature-Bug-1115-Job details pop-up displays "error getting job details"

tdei-ui/src/assets/api_spec.json, tdei-ui/src/components/AssignPoc/AssignPoc.js, tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/components/CreateProjectGroup/CreateProjectGroup.js, tdei-ui/src/components/CreateService/CreateService.js, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/components/ManagePoc/ManagePoc.js, tdei-ui/src/components/UserHeader/UserHeader.js, tdei-ui/src/hooks/roles/useApiKey.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css, tdei-ui/src/routes/ProjectGroup/ProjectGroup.js, tdei-ui/src/routes/Services/Services.js, tdei-ui/src/services/apiServices.js
- Added confidence calculation, BBox and dataset tag road, Quality metric calculation, to the existing list of jobs under job creation. 
- Added api spec json file in assets folder (to be replaced with latest json during CI/CD).
- Added description under every job type selected from api spec json file.
- Modified AuthProvider code bit to fix a minor issue.
=> Feature-1072-create job more options

tdei-ui/src/components/VerticalStepper/VerticalStepper.js
Fixed the bug : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1141
=> Feature-Bug-1141-Metadata file upload issue

.github/workflows/deploy_to_prod.yaml
Added prod environment workflow file
=> Added prod environment workflow

tdei-ui/src/components/JobJsonResponseModal/JobJsonResponseModal.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/services/apiServices.js, tdei-ui/src/utils/constant.js
- Added spatial join in create job options
=> Feature-1150-spatial join job creation

tdei-ui/src/components/AssignRoles/AssignRoles.js, tdei-ui/src/components/DeleteModal/DeleteModal.js, tdei-ui/src/routes/Datasets/DatasetsActions.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Members/Members.js, tdei-ui/src/routes/Services/Services.js, tdei-ui/src/utils/helper.js
Completed task -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1155/
1. Datasets List Page
- Remove disabled options from released datasets.
2. Jobs List Page
- Rename "Create New" button to "Create Job".
3. Members Page
- Rename "Assign role to new user" to "Assign roles" when accessed via "Manage User".
- Disable action button for the logged-in user, as logged in user cannot manage 
own roles.
- Disable email ID field when managing users.
- Add "Remove User" option
in the action button menu under "Manage Member".
- Display a confirmation popup when removing a user, with the message: "User will be removed from the project group".
- Format phone numbers in the members display.
4. Services Page
- Rename "Create New" to "Create Service".
5.Create Job -> OSW Convert
- Source format OSM …
=> Feature-1155-front end feedback changes

tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Services/CreateUpdateService.js, tdei-ui/src/services/apiServices.js
Added payload size check for request with json body.
=> Feature-task-1140: Json body payload restriction

tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/SchemaVersionDropdown.js
Fixed following issues :
1. https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1162/
2. https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1167/
=> Feature-Bug-1162-1167-Datasets list duplicate issue and schema input field to dropdown change

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Jobs/Jobs.js
=> Added filter and download result for quality metric

tdei-ui/src/routes/UploadDataset/Changeset.js, tdei-ui/src/utils/constant.js
- Completed task : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1182
- Changed default group name to TDEI Default
=> Feature-task-1182-Changeset file format and TDEI Default name change

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Jobs/CreateJob.js
- Added download file button for a completed confidence job. : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1184/
- Corrected format of attachment while creating a confidence job.
=> Feature-1184-Add download result for confidence calculation job

tdei-ui/src/components/ResetPassword/ResetPassword.js
- Added current password field and validation
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1180
=> Feature-1180- Add current password field in reset password page

tdei-ui/src/routes/UploadDataset/UploadDataset.js
Fixed bug: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1194
=> Feature-Bug-1194-Upload dataset description change

tdei-ui/src/components/ProjectGroupList/CustomDropdown.js, tdei-ui/src/components/ProjectGroupList/Dropdown.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Services/CreateUpdateService.js, tdei-ui/src/routes/UploadDataset/UploadDataset.js, tdei-ui/src/services/apiServices.js
Fixed following bugs as part of : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1263/
- Putting malformed JSON in the Service Boundaries gives no visible error message -> **Added json validation errors wherever post call is made with request body.**
- Place the following JSON for service boundaries, click Create and you receive correct error message (Error in creating Service. The first and last positions must be equivalent), click Create again without any change and you're taken to the Services page --> **Fixed back navigation issues.**
=> Feature-bug-1263-Bugs with "Create New Service" page in Staging

tdei-ui/src/assets/api_spec.json, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/QualityMetricAlgo.js, tdei-ui/src/services/apiServices.js
Added the following changes as per the task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1267
1. Removed the existing algorithm options etc. Added a dropdown component called Algorithm. with label Names - [Fixed, Intersection] and its [fixed,ixn].
2. Added a dropzone component which takes in geojson file (optional field).
3. Updated the spec document to get the latest field taglines.
=> Feature-1267-Change the Job input for Quality metric calculation

tdei-ui/src/components/VerifyComponent/EmailVerification.js, tdei-ui/src/components/VerifyComponent/PasswordResetConfirm.js, tdei-ui/src/components/VerifyComponent/style.module.css, tdei-ui/src/index.css, tdei-ui/src/routes/ForgotPassword/ForgotPassword.js, tdei-ui/src/routes/ForgotPassword/style.module.css, tdei-ui/src/routes/LoginPage/LoginPage.js, tdei-ui/src/routes/Register/Register.js, tdei-ui/src/routes/index.js
Added
-  Email verification flow.
-  Password recovery flow.
=> Feature-1273-Email address verification/validation/password recovery

tdei-ui/src/assets/api_spec.json, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/services/apiServices.js
=> Intersection quality job completed

tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/components/ReLoginModal/ReLoginModal.js, tdei-ui/src/components/ReLoginModal/ReLoginModal.module.css, tdei-ui/src/services/axiosService.js, tdei-ui/src/services/tokenEventEmitter.js
- When token expires : 
- Added Re-login modal for expired tokens when navigating within the app.
-  Logs the user out if they refresh the browser, with a popup saying session expired logging out.
=> Feature 1272 token expiry handling

tdei-ui/src/components/ToastMessage/ResponseToast.js, tdei-ui/src/routes/Services/CreateUpdateService.js
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1270/ : 
When user types in incorrect json while creating a service , fixed the following: 
1. Automatic disappear on error -> remove automation.
2. Invalid service boundary provided/ invalid geojson/ malformed service boundary. -> add proper message
=> Feature-task-1270-Create service error handling changes

tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js
Fixed the bug: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1285
=> Feature-Bug-1285-Clone upload file issue fix

tdei-ui/src/components/ReLoginModal/ReLoginModal.js, tdei-ui/src/services/axiosService.js
Fixed modal overlap and refresh token issue.
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1286
=> Feature-bug-1286-Session Expired Modal overlapping with api error Modal

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/services/apiServices.js
- Made quality metric file downloadable like other job formats.
=> Feature-Bug-1279-Quality metric job output is not downloadable

tdei-ui/src/components/AuthProvider/AuthProvider.js
Added window reload after successful re-login after session timeout.
=> Feature Reload after successful re-login

tdei-ui/src/services/axiosService.js
Fixed the bug: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1344
=> Feature-Bug-1344-Giving wrong credentials while logging in is showing session timeout modal

tdei-ui/src/components/DatePicker/DatePicker.js, tdei-ui/src/hooks/service/useGetDatasets.js, tdei-ui/src/hooks/service/useGetReleaseDatasets.js, tdei-ui/src/routes/Datasets/Datasets.module.css, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/routes/Datasets/SortRefreshComponent.js, tdei-ui/src/routes/Jobs/JobSortRefreshComponent.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/services/apiServices.js
Task -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1244/
- Initial UI with expanded filters and sorting. 
- Work in progress -> Autocomplete fields for project and service filter
=> Feature-task-1244-Expanded data discovery and filtering

tdei-ui/src/components/ProjectAutocomplete/ProjectAutocomplete.js, tdei-ui/src/components/ProjectAutocomplete/ProjectAutocomplete.module.css, tdei-ui/src/components/ServiceAutocomplete/ServiceAutocomplete.js, tdei-ui/src/components/ServiceAutocomplete/ServiceAutocomplete.module.css, tdei-ui/src/hooks/service/useGetAllServices.js, tdei-ui/src/hooks/service/useGetDatasets.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/services/apiServices.js
Task completed: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1352/
=> Feature-task-1352-service/project filter changes

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/components/ShowJobMessage/JobInputDescModal.js, tdei-ui/src/routes/Jobs/Jobs.module.css
Completed task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1351/
- Added an info button to every job, which on tap displays a pop up with request input parameters as key value pairs.
=> Feature task 1351 display job input description

tdei-ui/src/assets/api_spec.json, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/components/ShowJobMessage/JobInputDescModal.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/services/apiServices.js
- Added dataset union job creation UI -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1353/
- Fixed Issue -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1289/
- Refactored create job page code.
- Fixed job request input issue for bbox, spatial join and union types.
=> Feature-task-1353-1289-Union Job and Addition of missing job type filters

tdei-ui/src/components/DownloadModal/DownloadModal.js, tdei-ui/src/hooks/service/useGetDatasets.js, tdei-ui/src/hooks/service/useGetReleaseDatasets.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/services/apiServices.js
Task -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1357
- Added search by dataset id filter in datasets.
- Removed file version selection for released datasets.
=> Feature-task-1357-Feedback changes datasets page

tdei-ui/src/assets/api_spec.json, tdei-ui/src/components/ChipInput/ChipInput.js, tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetSummary.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js
- Task completed -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1314/
- When metadata file is uploaded, retrieved its contents and displayed in form below in edit/clone/dataset uploads.
- Task partially completed ->  https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1368/
- In Extended meta, added release_notes as new attribute and rename dkey_limitations_of_dataset to 'key_limitations'
=> Feature-1314-metadata upload changes

tdei-ui/src/components/DatePicker/DatePicker.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js
Task completed -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1368/
1. Made valid to & from required on publish.
2. After record is published, in edit metadata made valid from valid to mandatory.
=> Feature-1368-metadata publish field changes

tdei-ui/src/components/DatePicker/DatePicker.js, tdei-ui/src/components/DownloadModal/DownloadModal.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/Maintenance.js, tdei-ui/src/routes/UploadDataset/Metadata.js
- Tasks completed: 
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1372/
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1370/
- Bug Fixed: 
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1373
BUG FIX (zoomed out the image for understanding the fix):
=> Feature-task-1370-Datepicker changes-bug-1373-metadata file upload error

tdei-ui/src/routes/CloneDataset/CloneDataset.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js
Fixed the bug : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1375/
=> Feature-Bug-1375-Refreshing on edit/clone page is throwing error

tdei-ui/package.json, tdei-ui/src/components/DatePicker/DatePicker.js, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Datasets/DatasetRow.js
- Completed the following tasks :
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1374/ - Added Derived dataset id information with copy option (displayed only when a particular dataset has derived dataset id information not equal to "") in datasets list page.
- https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1390/ - Added ability to type in valid_to and valid_from in UI.
- In jobs page below status, instead of updated_at added Duration : 2min | 1hr | 1hr 30 min .
=> Feature-task-1374-1390-Derived dataset Copy and Datepicker manual entry changes

tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/Services/CreateUpdateService.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/SchemaVersionDropdown.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js, tdei-ui/src/services/apiServices.js
Fixed following bugs: 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1416/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1410/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1417/
=> Feature-Bug-1416-1410-1417-Create service generic error & Schema version picker fix

tdei-ui/src/services/apiServices.js
- corrected the `show_group_jobs` Boolean value in code. 
show_group_jobs = true
=> Feature-bug-1417-show group job filter correction

tdei-ui/src/services/apiServices.js
Changed source and target keys in OSW convert api call to `source_format`, `target_format`
=> Feature Task OSW convert key changes

tdei-ui/src/routes/Jobs/CreateJob.js
- Added json validation condition before submitting spatial join job.
=> Feature Bug 1468 - Spatial join json error fix

tdei-ui/src/routes/Services/CreateUpdateService.js
Fixed error pop-up display in create service for invalid polygon/multipolygon.
=> Feature bug create service error issue

tdei-ui/src/components/ResetPassword/ResetPassword.js, tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Datasets/DatasetsActions.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/Register/Register.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DropdownComponents/DataSource.js
- Fixed bugs [1522](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1522/) and [1527](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1527)
- Handled improper required fields issue in file upload for clone and edit metadata as well.
=> Feature-bug-1522-1527-Disable create workspace for flex and empy message error for OSW Dataset

tdei-ui/src/components/CreateProjectGroup/CreateProjectGroup.js, tdei-ui/src/routes/Datasets/DatasetsActions.js
Fixed the following issues:
1. [1547](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1547) : Edit/Create new project group with existing name doesn't throw any error.
2. [1363](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1363) :  Data incline enabled for all un-published datasets.
=> Feature-bug-1363-1547- Data incline and create project issues

tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js
- Changed version field's data type to string which accepts number in format "x or x.y".
=> Feature-Bug-1580-Dataset version parsing issue

tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/MetaDataForm.js, tdei-ui/src/routes/UploadDataset/Metadata.js
Moving dataset metadata version changes to stage
=> Dev to Stage

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/components/ResetPassword/ResetPassword.js, tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css, tdei-ui/src/routes/Register/Register.js, tdei-ui/src/utils/helper.js
Included updates as part of tasks [1578](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1578) and [1579](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1579):
1. Implemented an updated regular expression (regex) for password validation.
2. Added the created datetime to the job list page, indicates when each job was created.
=> Feature-task-1579-1578-Password and Jobs list changes

tdei-ui/package-lock.json, tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css
- Added abandoned status in jobs list filter.
=> Feature-task-1649-Abandoned status filter

tdei-ui/src/assets/api_spec.json, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/services/apiServices.js
Task [1670](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1670/) -> Added proximity as optional field in data union job creation.
=> Feature-task-1670-Data union proximity field addition

tdei-ui/public/terms.html, tdei-ui/src/components/SuccessModal/CustomModal.js, tdei-ui/src/index.css, tdei-ui/src/routes/Register/Register.js
Task [1669](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1669): Enhancements to Account Creation Flow
- Terms & Conditions Check:
When a user clicks on Create Account without accepting the Terms & Conditions, a popup appears with the message:
"Please accept Terms and Conditions to create your account"
The popup includes an OK button that, when clicked, returns the user to the registration form with all previously entered details preserved.
- Form Validation:
The Create Account button is now disabled if any required fields are not filled.
- UI Improvements:
The disabled Create Account button has been updated to display a grey background.
- Contact Email Update:
Replaced the old email help@accessmap.atlassian.net with the new email help@tdei.us.
=> Feature-task-1669-Terms and Conditions UI changes

tdei-ui/src/hooks/service/useGetServices.js, tdei-ui/src/routes/CloneDataset/CloneDataset.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/UploadDataset/ProjectGroupSelection.js, tdei-ui/src/routes/UploadDataset/ProjectGroupsList.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js, tdei-ui/src/services/apiServices.js
- Task[1715](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1715/) : Added project group selection step in clone dataset.
=> Feature-task-1715-Add select project group step in clone dataset UI

tdei-ui/src/hooks/projectGroup/useGetProjectGroupUsers.js, tdei-ui/src/hooks/roles/useIsMember.js, tdei-ui/src/hooks/service/useGetServices.js, tdei-ui/src/routes/CloneDataset/CloneDataset.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/Datasets/Datasets.js, tdei-ui/src/routes/Datasets/DatasetsActions.js, tdei-ui/src/routes/Datasets/DatasetsTabsContainer.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Services/Services.js, tdei-ui/src/routes/UploadDataset/ProjectGroupSelection.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js, tdei-ui/src/services/apiServices.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1723
Users with the ‘Member’ role in a project group:
1. Can read all datasets in the project group, including pre-release datasets.
2. Can read all released datasets from other project groups.
3. Cannot release datasets or create new datasets within the project group.
4. Have read-only access to datasets in the TDEI system.
5. Can view job details.
6. Can run jobs that do not modify datasets, such as validation and formatting jobs, but cannot run dataset road tagging jobs.
7. Users can have the ‘osw-data-generator’ role without the ‘Member’ role in a project group.
Tested **Impacted Areas for test cases**.
- Dataset Access Control:
- Verify that Members can read all datasets but cannot release or modify datasets.
- Confirm that Members …
=> Feature-task-1723-Handling 'member' role in a project group

tdei-ui/public/style.css, tdei-ui/public/terms.html
Azure DevOps Task #[1611](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1611)
---
- Updated the TDEI Terms & Conditions to reflect new clarifications on data sharing, attribution, and licensing.   
- Updated contact email to **help@tdei.us**.  
---
- Verify that the updated Terms & Conditions appear correctly in the registration flow.  
- Ensure that the email contact is updated to **help@tdei.us**.  
---
=> Feature- task-1611-Terms and conditions update

tdei-ui/public/terms.html
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1449](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1449)
Updated the Terms and Conditions to reflect new policies around data privacy, pre-release data status, licensing options, and data deletion processes.
- Verify the updated Terms and Conditions display correctly in the UI.
=> Feature-task-1449-Terms and conditions change

tdei-ui/src/components/AuthProvider/AuthProvider.js
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1774](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1774)
- When multiple portals (dev portal, stage portal) or multiple browser tabs of the same app are open and a new user logs in on one tab, the **current selected project group** gets overwritten in the other tab.  
- This triggers **continuous API calls** (particularly datasets listing) in a loop because the “old tab” repeatedly resets to the new user’s session data.  
- The network tab shows numerous repeated requests, and the UI flickers as it keeps trying to sync incompatible project group states across tabs.
**Refreshed Listening Logic**:  
- A small “force refresh” broadcast was added when a new user logs in, so other tabs detect this change and re‐verify the user context …
=> Feature-Bug-1774-Current selected project group keeps changing

.github/workflows/deploy_to_prod.yaml, .github/workflows/deploy_to_stage.yaml
This PR enhances the workflow to add dataviewer URLs in the environment file generation for both stage and production environments
=> Bugfix workflow correction

tdei-ui/src/routes/Feedback/Feedback.js, tdei-ui/src/services/apiServices.js
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2216](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2216)  
- **Download Feedback:** Renamed “Download CSV” to **“Download Feedback”** and added a popover for format selection.  
- **Format Options (Popover):** Added **CSV** and **GeoJSON** options.
- **API Integration:** Added "geojson" format to existing feedback download API;
- **Filename:** Confirm downloaded filename matches API header; otherwise defaults to `PG_<id>_issues.csv` or `PG_<id>_feedbacks.geojson`.  
- **Format Selection:** Popover opens from the button; CSV triggers download; GeoJSON triggers download with `format=geojson`.
=> Feature-Task-2216-Feedback GeoJson Download Option Addition
