tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/Datasets/DatasetsActions.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js, tdei-ui/src/services/apiServices.js
Fixed the bug -> https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1041 : 
* Dataset id as download file name.
* Clone -> All released datasets -> enable for data generators, poc, admin.
* Services for clone only existing dataset’s service type should be displayed.
* Service id reset when project group is reset.
* Pre-populate schema version for clone dataset.
Screenshots:
=> Feature-Bug-1041-Dataset download name, clone dataset service list changes

tdei-ui/src/hooks/jobs/useGetJobDetails.js, tdei-ui/src/hooks/jobs/useGetJobs.js, tdei-ui/src/hooks/service/useGetDatasets.js, tdei-ui/src/hooks/service/useGetReleaseDatasets.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/services/apiServices.js
- Added functionality to the filter to display all/submitted by me jobs.
- Fixed the issue: jobs and dataset listing page make 2 duplicate calls for listing.
Test Case Verified for bug 1102: 
1. **Submitted by me** only displays the ones created by the logged in user.
2. **All** displays all the jobs belonging to that project group.
- Tested with 2 users belonging to the same project group: 
-- A can see all jobs belonging to that project group in jobs list with filter **All**. Which implies, A can also see B's jobs in jobs list with filter **All**.
-- A can see only A's jobs list with filter **Submitted by me**.
-- Vice versa.
User A of project group Asian Leisure Pvt Ltd with filter **Submitted by me**: 
User A of project group Asian Leisure Pvt Ltd with filter **All**: 
User B of …
=> Feature Bug- 1102: Frontend 'show' filter with 'submitted by me' and 'all'

tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.module.css
Fixed the bug: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1193
Fix made: 
- Replaced root component **Layout** which by default checks only if user is poc or admin with <div>
- The parent page **jobs list** already has a check, if ---> **roles.includes("poc") || roles.includes("flex_data_generator") || roles.includes("osw_data_generator") || roles.includes("pathways_data_generator")**
So, by default, any user who is not able to see jobs list also cannot access create job page.
=> Feature-Bug-1193-Unable to view create job page although the user is data generator

tdei-ui/src/components/ResetPassword/ResetPassword.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/LoginPage/LoginPage.js, tdei-ui/src/routes/Register/Register.js, tdei-ui/src/routes/Services/CreateUpdateService.js, tdei-ui/src/utils/helper.js
Fixed the following issues as a part of : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1216
- On demand jobs creation, change text: Job has been created -> Job has been completed!
- hide/unhide password in all login related screens.
- Project id showing as default for all in edit service -> as admin user.
- “null” next to first name. Need to handle last name display when it is undefined.
=> Feature-Bug-1216- Front end issues fix and password field hide/unhide password 

tdei-ui/src/components/DownloadModal/DownloadModal.js, tdei-ui/src/components/DropZone/Dropzone.js, tdei-ui/src/routes/Datasets/MyDatasets.js, tdei-ui/src/routes/Datasets/ReleasedDatasets.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/services/apiServices.js
Task 1 - https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1345/
- There is already an existing condition for OSW convert job where depending on the source format, accepted file format changes. i,e OSM -> '.pbf', '.osm', '.xml' and OSW -> 'zip'. Earlier prior to source selection,'. zip' file upload was accepted. Now disabled file upload without source selection.
Task 2 - https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1341/
- Added file version and format selection for OSW dataset download by displaying a selection modal. Default values 'OSW 'format and 'latest' version are selected.
=> Feature task-1345-1341-OSW convert and download job changes

tdei-ui/src/components/Header/Header.js, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitch.js, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcher.js, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcher.module.css, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcherDropDown.js, tdei-ui/src/hooks/roles/useProjectGroupRoles.js, tdei-ui/src/routes/Root/Root.js, tdei-ui/src/routes/index.js, tdei-ui/src/services/apiServices.js, tdei-ui/src/utils/constant.js
- Added pagination to projects groups list switch UI.
- Made project groups tab visible to non-admin (only project groups switcher).
=> Feature-Task-1710-Frontend UI not showing all the project groups

tdei-ui/src/components/AssignRoles/AssignRoles.js, tdei-ui/src/components/DeleteModal/DeleteModal.js, tdei-ui/src/routes/Members/Members.js
Bug [1713](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1713) - When we ‘assign roles’ with no selected roles, added a warning ‘Are you sure you want to remove the user from this project group?`
=> Feature-bug-1713-Update Assign roles modal

tdei-ui/src/components/AssignRoles/AssignRoles.js, tdei-ui/src/components/DeleteModal/DeleteModal.js, tdei-ui/src/components/UserHeader/UserHeader.js, tdei-ui/src/components/UserHeader/UserHeader.module.css, tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/Services/Services.module.css, tdei-ui/src/routes/UploadDataset/ProjectGroupSelection.js, tdei-ui/src/routes/UploadDataset/ServiceUpload.js
[Azure DevOps Task 1732](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1732)  
---
- ‘Member’ description updated to "A standard project group member with limited permissions." in *Assign Role* (Previously displaying API description).  
---
- **Updated error message**:  
> "You need **x_data_generator** role to clone this dataset**
- It now checks whether the current user has **x_data_generator**, **poc**, or **admin** role.
- **Services Step UI Updated**:  
- Displays **selected project group** in step:  
> *Select Service from `<project_group_name>`:*  
---
- Changed "Revoke Permissions" modal header to → **"Remove User"**.  
- Updated "Revoke" button text to → **"Remove"** to maintain consistency.  
- **Changed success message after user removal**:  
> *User removed successfully. …
=> Feature-task-1732-Member access and Api key modules demo changes

tdei-ui/public/style.css, tdei-ui/public/terms.html, tdei-ui/src/components/UserHeader/UserHeader.js, tdei-ui/src/components/UserHeader/UserHeader.module.css, tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1734
- Updated the error message for cloning datasets. The new message specifies the required role and project group format:  
**Old:** "You need _data_generator role to clone this project group."  
**New:** "To clone this dataset to project group Y, you need x_data_generator role in Y."  
- Fixed the API key width by applying a constant width.  
- Added a "Last Updated" timestamp to the Terms & Conditions page.  
1. **Dataset Cloning Message Update**  
- Verify that the updated message appears correctly when a user without the required role attempts to clone a dataset.  
- Ensure the project group name (`Y`) and required role (`x_data_generator`) are dynamically populated based on the context.  
2. **API Key Width Fix**  
- Confirm that …
=> Feature-task-1734-Front-End: Member alert message changes and UI corrections

tdei-ui/src/components/UserHeader/UserHeader.module.css
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1722
- The API Key container (`.maskedKey`) was causing horizontal scrolling on few layouts due to changes added for smaller screen configurations. 
- On certain screen sizes, the layout adjustments led to unintended overflow behavior.  
- Updated `.maskedKey` to remove scrolling on both large and small screens:
- Kept `min-width: 525px;` for maintaining readability on large screens.  
- Set `max-width: 48%;` to ensure responsiveness across different screen sizes.  
- Added `overflow: hidden;` and `flex-shrink: 1;` to allow flexibility without causing scroll.  
- Updated `.apiKey` to ensure better layout behavior:
- Prevented unnecessary scrolling by keeping `white-space: nowrap;` and `overflow: hidden;`.  
- API Key container …
=> Feature-Bug-1743-API Key in dashboard displayed with scroll

tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/components/Header/Header.js, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitch.js, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcherDropDown.js, tdei-ui/src/components/ReLoginModal/ReLoginModal.js, tdei-ui/src/components/ResetPassword/ResetPassword.js, tdei-ui/src/hooks/service/useGetReleaseDatasets.js, tdei-ui/src/services/axiosService.js, tdei-ui/src/store/projectGroupRoles.slice.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1711
- Ensured that the selected project group persists across browser refresh and back events instead of defaulting to the first available project.
- Selected project group now remains active until logout or explicit selection of another project.
- Fixed cross-tab synchronization, ensuring that project group selection updates automatically across multiple open tabs.
- Cleared project group selection upon logout to prevent unauthorized usage.
---
| Test Case | Steps | Expected Behavior | Pass/Fail |
|-----------|-------|------------------|-----------|
| **Login** | By default, the first project group in the list gets selected. | The first project group in the list gets selected. | Pass |
| **Page Refresh** | 1. Select a project group <br> …
=> Feature-task-1744-Remember the current selected project group until logout

tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcher.module.css, tdei-ui/src/components/ProjectGroupSwitcher/ProjectGroupSwitcherDropDown.js, tdei-ui/src/routes/Datasets/DatasetRow.js, tdei-ui/src/routes/Datasets/DatasetsActions.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1756
- Added a 'Download Metadata' action button in the datasets list dropdown.
- Clicking the 'Download Metadata' button extracts the `metadata` field from the dataset and downloads it as a JSON file.
- Implemented error handling to prevent downloading an empty or missing metadata file.
- Made this button accessible to roles 'members' and above.
- Verify that the 'Download Metadata' button appears in the dropdown action menu.
- Ensure that clicking the button triggers a metadata JSON file download.
- Confirm that the downloaded file contains valid metadata.
--- 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1749
- Added 'Current Project Group' section in the dropdown.
- Added 'Switch Project Group' header.
- Ensured …
=> Feature-task-1756-Add download metadata action button & Project Group Selection Dropdown UI Changes

tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/services/axiosService.js
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1760](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1760)
- When a user **visits the portal for the first time**, a **"Session expired"** error is displayed incorrectly.  
- This message should only appear when **both access token and refresh token are expired** and the user **refreshes or clicks the back button**.  
- In some rare cases, when an **access token expires**, the user gets a **401 error**, the **refresh token request succeeds**, but the **UI does not reflect the new token** and remains in an incorrect state.
- Ensured the "Session expired" message only appears when both tokens are expired and the user refreshes or clicks the back button.  
-  - Before: When the token was refreshed, the UI did not update, because React …
=> Feature-bug-1760-Session Expired Error is shown even on fresh login & UI not updating on new refresh token

tdei-ui/src/components/VerticalStepper/VerticalStepper.js, tdei-ui/src/routes/CloneDataset/CloneDatasetStepper.js, tdei-ui/src/routes/EditMetaData/EditMetaData.js, tdei-ui/src/routes/UploadDataset/MetaDataForm/DatasetDetails.js
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1778](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1778)
- Added helper text to the **Custom Metadata** field in the `DatasetDetails` form to indicate that the input must be a valid JSON string. Example JSON structure (`{"key": "value"}`) is shown as guidance for users.  
- Implemented validation logic to check if the `custom_metadata` field contains valid JSON when the form is submitted. An appropriate error is shown if the JSON is malformed.
- Verify that the **Custom Metadata** field displays the helper text: _"Enter metadata as a valid JSON string. e.g., {'{"key": "value"}'}"_  
- Enter valid and invalid JSON in the Custom Metadata field and try submitting the form.  
- Ensure an error appears on submit if the JSON is invalid, …
=> Feature-task-1778-Custom Metadata JSON validation

tdei-ui/src/components/AuthProvider/AuthProvider.js, tdei-ui/src/components/Header/Header.js, tdei-ui/src/components/ProjectAutocomplete/ProjectAutocomplete.js, tdei-ui/src/components/ReLoginModal/ReLoginModal.js, tdei-ui/src/hooks/useIsDataTypeGenerator.js, tdei-ui/src/routes/Datasets/DatasetsActions.js, tdei-ui/src/routes/Datasets/MyDatasets.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1787
- Users with roles like `osw_data_generator`, `flex_data_generator`, etc. could not see the **Release** option in the UI for datasets of their respective `data_type`.
- The existing logic for `canPublish` only allowed POC users or Admins to see the "Release" option.
- As a result, even valid generator roles could not release their datasets.
- Introduced a new hook: `useIsDataTypeGenerator(data_type)`
- This hook checks if the user has a role matching the pattern `<data_type>_data_generator`.
- It pulls role info from the selected project group.
- Updated the `canPublish` logic in `DatasetsActions.js`:
```
const canPublish = isPocUser || user?.isAdmin || isDataTypeGenerator;
```
| Role Combination           | Dataset data_type | …
=> Feature-Bug-1787 -API Key Error and Release Access issue for x_data_generator & Bug-1774

.gitignore, tdei-ui/src/components/AssignRoles/AssignRoles.js, tdei-ui/src/hooks/roles/useAssignRoles.js
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1889
- POC trying to add roles/permission to the user which is not registered on TDEI system, API throws 404 user not part of the system error. 
- On UI error message shown was generic fallback error instead of showing API error. This is due to wrong error property mapping.
- Corrected the property mapping and displayed the user friendly message.
- Assign new roles
- Manage existing user roles
=> bug fix 1889

tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2066  
In job list page, when we enter a job ID which is not in the system, the API returns a 404. On the client side we need to show an empty result.  
Right now the user sees the generic error “Error loading project group list.”  
---
- **[NEW] Added missing condition** to handle 500 errors in:
```ts
if (
isError && (
error?.response?.status === 404 ||
error?.response?.status === 400 ||
error?.response?.status === 500
)
)
=> Bug-2066 : Wrong job Id Error Added missed out cases

tdei-ui/src/components/JobListItem/JobListItem.js, tdei-ui/src/routes/Jobs/CreateJob.js, tdei-ui/src/routes/Jobs/Jobs.js, tdei-ui/src/routes/Jobs/Jobs.module.css
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2113 
1) Login to TDEI 
2) Go to Jobs
3) Click on the "Created On" column
4) Results do not resort. Clicking on it again does not invert the result.
---
- Date sort for Created On
- Unified sortData 
- Expanded `sortData()` to handle `job_type`, `job_id`, `status`, `created_at`, and `requested_by`.  
- Toggled sort direction on repeated clicks.  
---
- Sort by Job Type 
1. Click “Job Type” header → list sorts A->Z  
2. Click again -> Z->A  
- Sort by Job ID
1. Click “Job ID” header -> numeric ascending
2. Click again -> numeric descending  
- Sort by Status  
1. Click “Status” -> alphabetical ascending   
2. Click again → reverse order  
- Sort by Created On  
1. Click “Created On” -> chronological ascending (oldest -> newest)  
2. Click …
=> Bug-2113-Sort by created on & Bug-2112-Rename Dataset BBox

tdei-ui/src/routes/Datasets/DatasetRow.js
This pull request makes targeted improvements to the `DatasetRow` component in `tdei-ui/src/routes/Datasets/DatasetRow.js` to ensure that data viewer actions and badges are only available when both the project group and the dataset explicitly allow data viewer access. This enhances permission checks and UI accuracy.
**Permission and UI logic improvements:**
* Added a check for `project_group.data_viewer_allowed` to the conditions that determine if the data viewer action is available, ensuring that both user role and project group permissions are considered.
* Updated the rendering condition for the data viewer badge to require both `project_group.data_viewer_allowed` and `data_viewer_allowed` to be true, preventing the badge from displaying when either is not permitted. …
=> fixed updating dataviewer badge on data set along with the project group level status

tdei-ui/src/hooks/feedback/useDownloadPGFeedbacks.js, tdei-ui/src/routes/Feedback/Feedback.js, tdei-ui/src/services/apiServices.js
[https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2216](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2216)  
- **Download CSV API Integration:** Integrated API for “Download CSV” button .  
- **Project Group Scope:** Downloads all feedback for the selected project group as CSV (no filters applied yet).    
- **Loading State:** Verify button text changes to *“Downloading CSV…”* until download completes or fails.  
- **Success/Error Toast:** Confirm correct toast messages on success and error scenarios.  
- **Filename:** Check if downloaded file name matches API response.  
- **Integration with Filters:** Download should remain independent of filters for now; will extend in future tasks if required.
=> Feature-Task-2216-Download Feedback API Integration
